### ISSUE TITLE
Mac link not working

### ISSUE THREAD

**Issue by SellingFun** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#1]
Windows link is working but Mac link takes to 404 page...

**Comment by shopgoodwill-auction-sniper** [comment]
Hi SellingFun, we are aware of the issue for now all we have is the windows version available until we renew the Mac version...

Best Regards,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi SellingFun, 

We are excited to announce we have finally released the Mac version of the ShopGoodwill Auction Sniper, you can now download it from our website homepage here:

http://Snipeable.com

Please let us know if you need further assistance.

Thank you!
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi SellingFun,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
