### ISSUE TITLE
no liscense attached

### ISSUE THREAD

**Issue by skratzer12** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#10]
hello, 

Ive bought the liscense, copy and pasted the liscense. Now the program is still saying i dont have a liscense. 

Please assist

**Comment by skratzer12** [comment]
![image](https://github.com/user-attachments/assets/8b127925-5798-4a36-888b-3a2c47788cd8)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi which license did you purchase, and the amount/date you paid?

**Comment by skratzer12** [comment]
hello, i paid on july 16th. prepaid for a month unlimited

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

Thank you for your patience as we resolved the issue you reported and released an update for it, I am glad to report that the update is now released and you can download the latest version from our main page below, but first please uninstall the old version and then install the new version:

[http://Snipeable.com](http://Snipeable.com)

Also we have activated and extended your license by 1 month starting from tomorrow now it will expire or renew on 8/21/2024 manually at your discretion.

Best Regards,
Customer Service
