### ISSUE TITLE
Snipes not registering

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#11]
I have yet to have the app to work.  Looks it's trying but did not make the bid.   

![IMG_3047 2](https://github.com/user-attachments/assets/15034e5a-c387-4b86-9cb9-dd20c6b08d67)
![IMG_3046 2](https://github.com/user-attachments/assets/9f0df70a-874b-4e83-950b-899eca667028)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

Thank you for your patience as we resolved the issue you reported and released an update for it, I am glad to report that the update is now released and you can download the latest version from our main page below, but first please uninstall the old version and then install the new version:

[http://Snipeable.com](http://Snipeable.com)

**Comment by jake35th** [comment]
Will I have to register?  Sent from my iPhoneOn Jul 20, 2024, at 9:20 PM, ShopGoodwill Auction Sniper ***@***.***> wrote:﻿
Hi,
Thank you for your patience as we resolved the issue you reported and released an update for it, I am glad to report that the update is now released and you can download the latest version from our main page below, but first please uninstall the old version and then install the new version:
http://Snipeable.com

**Comment by shopgoodwill-auction-sniper** [comment]
Only if you haven't registered yet.
