### ISSUE TITLE
License Not Properly Activated

### ISSUE THREAD

**Issue by mrwick16** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#12]
I purchased a 1 month unlimited license but the app is not recognizing my license.
Please help so that I can use what I paid for

[Window Title]
Bid Sniper

[Content]
To continue using this app, please purchase a license and register your unique machine ID on Snipeable.com

Your unique machine ID is:
D466A71087C6A383

Please copy and paste this code to register your machine.

[OK]

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mrwick16,

I have activated your license and extended until 08-22-2024!

Please let us know if we can be of further assistance.

Best regards,
Customer service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mrwick16,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
