### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by skratzer12** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#13]
Hello again,

i cannot download the file since windows security says its contains a virus and will not download.

**Comment by skratzer12** [comment]
Its also trying to install a .vbs file and its not opening it in the microsoft store as an app

**Comment by shopgoodwill-auction-sniper** [comment]
Hi skratzer,

We have changed the download link on our homepage, please try again...

Also we have cancelled our contract with the app stores, so please uninstall that one as it old now and is no longer maintained, there are plenty of instructions on our homepage on how to install please review our homepage again.

Best Regards,
Technical Support

**Comment by shopgoodwill-auction-sniper** [comment]
PS the new file is a zip so if you are still downloading the other vbs file please wait about 10 to 15 minutes and click refresh on our homepage and click on the download link again and you should get the zip file this time!
