### ISSUE TITLE
Not Bidding

### ISSUE THREAD

**Issue by mrwick16** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#14]
I have tried to bid on 3 different items. I restarted and my bids are still not being made. 
The last one my bid would've been the winning bid and no other bids were made so I know it wasn't an issue of being outbid.

**Comment by shopgoodwill-auction-sniper** [comment]
please uninstall the version from the App Store if that is the version you installed and instead install the latest best version from our homepage at: 

[http://Snipeable.com](http://Snipeable.com)

**Comment by mrwick16** [comment]
I did download it directly today, not from the app store

**Comment by mrwick16** [comment]
I am uninstalling & reinstalling now.

**Comment by mrwick16** [comment]
I uninstalled & re-installed directly from the page and it is still not working. I entered in what would've been the winning bid & no bid was entered at all.
![image](https://github.com/user-attachments/assets/9cb9aa9a-511e-4f33-8133-345bb932a658)

**Comment by shopgoodwill-auction-sniper** [comment]
can you please try adding a snipe and then confirm if the date/time listed in the software is correct and reflects what is displayed on the shopgoodwill time as the auction end datetime?

**Comment by mrwick16** [comment]
No, the times are off by 2hours.
Auction ends at 10pm Pacific but the snipe says its set for 12am.

I am located in the Central Time Zone.

How do I fixe this?

**Comment by mrwick16** [comment]
Please advise on how this can be fixed?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi MrWick16,

We have released an update with the timezone fix, you can download it from our homepage:

http://Snipeable.com

Please notice the datetime this time when you add an item and ensure it is displaying the correct auction end datetime!

Please let us know if we can be further assistance...

Best Regards,
Customer Service

**Comment by mrwick16** [comment]
I uninstalled & reinstalled. It worked a few times and then it stopped working. 

Now it shows the same time as what is shown online i.e. 11:49 AM but now it thinks the time has passed because I am in the Central Time Zone
![image](https://github.com/user-attachments/assets/25c7ef67-efab-4ed7-a702-dec2efe6cd25)
![image](https://github.com/user-attachments/assets/17559531-1521-43b2-b0aa-c932887bb571)

 I have spent a lot of time trying to get this to work and still haven't able to use this...

**Comment by shopgoodwill-auction-sniper** [comment]
Ok, we will look into this today but your message is a little confusing because first you mention it worked a couple times then you said it doesn't work, well did it work or didn't it? It's important you describe exactly what you are experiencing correctly so we can properly diagnose the problem? So if I understand you correctly it thinks you're in PT time which is the shopgoodwill time zone but you are in central time is that correct?

**Comment by mrwick16** [comment]
It appeared to work twice. Since then it has not worked. I have restarted multiple times hoping it would start working again but it does not.

Yes, it appears to think I am in the PT time zone but I am in Central Time Zone.

**Comment by shopgoodwill-auction-sniper** [comment]
Thank you for clarifying, ok so if it worked twice already that means the issue is not related to timezone, but something else, so let us look into this today and hopefully we will have an update for you today to fix the issue...

Best Regards,
Technical Support

**Comment by shopgoodwill-auction-sniper** [comment]
Why did you say it thinks the time has passed already on the auction, so you added the auction and then it immediately went to missed status? Is that what you are saying?

**Comment by mrwick16** [comment]
Correction: It worked once on Monday 7/22 on an auction that closed at 8:03pm Pacific. It hasn’t worked since then.

Yes, that is correct the last 2 auctions I added said it was saved successfully but then missed because they showed that they had already passed. I will add a screenshot of the last one I tried that is stuck

**Comment by mrwick16** [comment]
![image](https://github.com/user-attachments/assets/9c8066d2-fc36-478d-b909-8bea832a4dc7)
