### ISSUE TITLE
taken money 

### ISSUE THREAD

**Issue by jlm861** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#15]
my money has been taken with my ID and it wont let me place more bids.Unique machine Id: B514E3BA1FA28DF4

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jlm861,

We have activated your license, please try again now...

Best Regards,
Customer Service

**Comment by jlm861** [comment]
It worked for two of my bids but has since stopped working

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jlm861,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
