### ISSUE TITLE
Missed 

### ISSUE THREAD

**Issue by skratzer12** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#16]
All my auctions that were scheduled was within 3 hours of the time going up on the auction but time wasnt up yet. They went from waiting to missed, and then it didnt bid on any of them. 

What could be going on?

**Comment by skratzer12** [comment]
I canceled the bids, i remade them. And once i remade them it says waiting for a few seconds and then goes to missed and stays at missed. I have tried a few and its not bidding.

**Comment by shopgoodwill-auction-sniper** [comment]
Sounds like you have the old version installed uninstall the current version from your computer first and then install the latest version from our homepage at Snipeable.com that should solve your issue.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

We have released a new update with the latest fixes, please download it from our homepage at Snipeable.com

Please let us know if we can be of further assistance.

Thank you,
Customer Service
