### ISSUE TITLE
having trouble buying a license

### ISSUE THREAD

**Issue by beems333** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#17]
How to I buy a license? I successfully installed the program and submitted a trial bid but when I open buy.htm in my web browser none of the buttons respond except close.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

We have released a new update with the licensing update, please download it from our homepage at Snipeable.com

Please let us know if we can be of further assistance.

Thank you,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi beem333,

We have released a new version of Bid Sniper that fixes the issue you were experiencing, please try to installing it again from our homepage at Snipeable.com and if you have any further issues please let us know...

Thank you!
Customer Service

**Comment by beems333** [comment]
Thank you the new version fixed my issue and I was able to buy the listing but I have another question. Does my computer have to be on for the bidding to take place or will the snipe still work if my computer is on screen saver and or in sleep mode? Thanks for your help!

**Comment by shopgoodwill-auction-sniper** [comment]
You're welcome, we have refunded your initial payment, as it is complimentary, we appreciate your business, thank you!

Best regards,
Customer Service

**Comment by beems333** [comment]
I just had two auctions that completed that said sniped! but the winners were under my snipe amount and no bid was made under my user name. 
<img width="583" alt="Screenshot 2024-07-29 at 6 50 07 PM" src="https://github.com/user-attachments/assets/7e71185f-3f9d-49f6-852c-87555e63b873">

Does this service actually work at all?

**Comment by beems333** [comment]
I just lost another auction that said it was Sniped but sold for under my snipe amount

**Comment by shopgoodwill-auction-sniper** [comment]
What time zone are you in? Is the auction date time correct on your display after you add the auction?

**Comment by beems333** [comment]
yes the time is correct. I was just able to successfully snipe an auction because I was on the same page as the auction when the snipe executed. if i need to do this for every snipe I will only be able to set one snipe at a time, haveing to navigate to the auction page prior to every snipe.

**Comment by beems333** [comment]
is there a way to run multiple instances of snipeable at a time or create tabs so i can set up multiple snipes that will be successfull?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, 

We just released a new version tonight that solves the issue you are experiencing, please download and install it from our homepage at Snipeable.com 

Best Regards,
Technical Support

**Comment by shopgoodwill-auction-sniper** [comment]
Hi beems333,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
