### ISSUE TITLE
worked for two and then stopped 

### ISSUE THREAD

**Issue by jlm861** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#18]
it bid on two of my items but not the rest. the newest version has been installed.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jlm861,

Thank you for your patience as diagnosed the issue, I am glad to report we have released an update with the fix, you can now download it from our home page at Snipeable.com

Please let us know if we can be of further assistance.

Thank you,
Customer Service

**Comment by jlm861** [comment]
This error message comes up for the new code: An error occurred during the installation. Node file not found in the expected location.

**Comment by shopgoodwill-auction-sniper** [comment]
That error means something interrupted the installation, please try deleting the installation files you downloaded and then re-download a fresh copy from our homepage at Snipeable.com but this time restart your computer before you start the installation to ensure there are no locked files and that should solve the issue but if it persists please let us know.
