### ISSUE TITLE
Worked Once & stopped Working - Please help

### ISSUE THREAD

**Issue by mrwick16** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#19]
Correction: It worked once on Monday 7/22 on an auction that closed at 8:03pm Pacific. It hasn’t worked since then.

Yes, that is correct the last 2 auctions I added said it was saved successfully but then missed because they showed that they had already passed. I will add a screenshot of the last one I tried that is stuck

_Originally posted by @mrwick16 in https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/issues/14#issuecomment-2249372888_

**Comment by mrwick16** [comment]
![image](https://github.com/user-attachments/assets/548ae274-7e65-481e-a80e-475104023631)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

We have released a new update with all the latest fixes, please download it from our homepage at Snipeable.com

Please let us know if we can be of further assistance.

Thank you,
Customer Service
