### ISSUE TITLE
**Urgent** Issues with Bid Sniper for shopgoodwill.com

### ISSUE THREAD

**Issue by merchantmogul** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#2]
Hi, I have paid for your 6 month subscription. so I have been using your app for a while. but now when I try to use it for bids on shopgoodwill, after adding some bids for multiple items, maybe one or two will fire off but the others wont fire off a bid. the app is broken.

Can someone please help?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchant mogul,

Sometimes ShopGoodwill prevents bidding on an item if there already a few won auctions on your account that have not yet been paid for, so most probably you are experiencing some kind of a limit imposed by ShopGoodwill.com, so the best way to test that out is to let it win a few items that are unpaid and then go try to manually place another bid on another item and if you see that shop goodwill.com states an error saying you can't bid on anymore items until your other items are paid for then you will know what the issue is...

Hope that helps...

Please let us know if the problem still persists.

Thank you,
Customer Service

**Comment by merchantmogul** [comment]
Hi, No that's not the problem.

I've been bidding on shopgoodwill for years and I often have over 15-20
live "won" items that I haven't even paid for and I'm still able to bid on
other items with no issues.

also, I had been using the bid sniper with many items I had won using the
sniper tool with no issues. But in just the last couple of days all of a
sudden the app is not bidding.

I even made sure I have NO pending items that need to be paid. I paid all
items but the bid sniper tool is still not firing off the winning bids that
i place.

also it's often very slow to load the bids I place. so something is
definitely wrong with the app.

please advise. Thanks

**Comment by merchantmogul** [comment]
Hi, No that's not the problem. 
I've been bidding on shopgoodwill for years and I often have over 15-20 live "won" items that I haven't even paid for and I'm still able to bid on other items with no issues.
also, I had been using the bid sniper with many items I had won using the sniper tool with no issues. But in just the last couple of days all of a sudden the app is not bidding.
I even made sure I have NO pending items that need to be paid. I paid all items but the bid sniper tool is still not firing off the winning bids that i place.
also it's often very slow to load the bids I place. so something is definitely wrong with the app.
please advise. Thanks

**Comment by merchantmogul** [comment]
Hi, No that's not the problem.

I've been bidding on shopgoodwill for years and I often have over 15-20
live "won" items that I haven't even paid for and I'm still able to bid on
other items with no issues.

also, I had been using the bid sniper with many items I had won using the
sniper tool with no issues. But in just the last couple of days all of a
sudden the app is not bidding.

I even made sure I have NO pending items that need to be paid. I paid all
items but the bid sniper tool is still not firing off the winning bids that
i place.

also it's often very slow to load the bids I place. so something is
definitely wrong with the app.

please advise. Thanks

**Comment by BuffySt** [comment]
Yeah similar problem here. Keep getting errors and no wins. Paid as well and seems like we got worked

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchantmogul,

Great news, we have released a new major version of Bid Sniper which fixes the issue you reported! You can download the latest version of the App Store here:

https://apps.microsoft.com/detail/9NLHNKNJM66J

**Comment by merchantmogul** [comment]
> Hi merchantmogul,
> 
> Great news, we have released a new major version of Bid Sniper which fixes the issue you reported! You can download the latest version of the App Store here:
> 
> https://apps.microsoft.com/detail/9NLHNKNJM66J

But when I try to use the new version it says I need to pay for license but i have alrady paid for a license. 

Can you please fix this?

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/0e032b6b-3b36-4f8f-a54f-8041b7f7b5e7)
![Screenshot 2024-07-04 192832](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/e5edf821-b295-4352-ac29-c51c41514b22)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchant mogul, 

We have reactivated your 6 month license on our new licensing system, so it should work fine now without asking you to pay again!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchantmogul,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
