### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by jlm861** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#20]
error message comes up when trying to download the new code: 'An error occurred during the installation. Node file not found in the expected location'

**Comment by jlm861** [comment]
Resolved

**Comment by jlm861** [comment]
I bought 5 but only two of them actually worked? now it says i need to buy more?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, it takes into account the snipes as you add the auction items in the app and not whether or not the auction was won or lost, so please ensure you only add items that you actually want to pursue 100% as each time you add an item and remove it counts as 1 snipe added/removed! 

Best Regards,
Customer Service

**Comment by jlm861** [comment]
Hi, yes i understand this. But three of them simply did not work at fault of the app not working properly. It wasnt that they simply lost.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jlm861,

We have released a new update today that contains some fixes, please download from our homepage at Snipeable.com 

Best Regards,
Technical Support

**Comment by jlm861** [comment]
none of my items were bid on. had purchased unlimited for the month

**Comment by shopgoodwill-auction-sniper** [comment]
jlm861, your comment makes no sense, we are now refusing service to you, you are blocked from using our service Goodbye

**Comment by jlm861** [comment]
It just goes straight to missed before the auction has begun

**Comment by jlm861** [comment]
This is unfair. I paid for unlimited snipes for a month. I set up multiple bids and none of my items were actually bid on by the app?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jlm861,

We apologize for that encounter you had with the previous customer service rep, we have relieved that customer service rep from their duties. I will be assisting you now, can you please try to installing Bid Sniper again from our Snipeable.com and if you have any further issues please let us know!

Thank you,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, 

We just released a new version tonight that solves the issue you are experiencing, please download and install it from our homepage at Snipeable.com 

Best Regards,
Technical Support
