### ISSUE TITLE
License not recognized

### ISSUE THREAD

**Issue by mrwick16** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#21]
I have downloaded the new version and now it is once again not recognizing the license i bought. 
Please help make this work.

D466A71087C6A383

**Comment by shopgoodwill-auction-sniper** [comment]
Hi MrWick16,

Our apologies, we were forced to change the licensing system in the latest release so you will have to purchase again and then we can refund you from here, so just let us know when you have purchased it again thru the software and your name and payment amount and we will refund the payment ASAP.

Best regards,
Customer Service

**Comment by mrwick16** [comment]
I am trying to make the payment but nothing is happening when I click pay. I restarted and it still doesn't work.

**Comment by shopgoodwill-auction-sniper** [comment]
What OS are you on Windows or Mac? Can you please download a fresh copy of the latest version from our homepage at Snipeable.com and install because we updated today to the latest version?

Thank you,

Customer Service

**Comment by mrwick16** [comment]
I already downloaded the newest version tonight. I deleted the previous version & downloaded it. I am on windows

**Comment by shopgoodwill-auction-sniper** [comment]
We understand, but we just updated it again about 1 hour ago because the packaging was incorrect.

**Comment by shopgoodwill-auction-sniper** [comment]
also which method of installation are you using command prompt, PowerShell or are you directly downloading the installer and running it? This information can help us reproduce the issue and resolve for you faster!

**Comment by mrwick16** [comment]
I downloaded it directly from the zip file. I thought that was what you wanted me to do? Tell me which way is best.

Still didn't work right. I tried to pay but it gets stuck at the pay screen and does not continue.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mrwick16,

We have released a new update today again that contains some fixes, please download from our homepage at Snipeable.com 

Best Regards,
Technical Support

**Comment by mrwick16** [comment]
Now when I go to download it is being blocked and marked as a dangerous download. I have tried this so many times now. Do you not have anyone testing this once you make the updates? 

I paid for this service but it feels like I am the one working for free being the tester. Can you please give me a seriously upgraded license if I do continue to try to make this work?

**Comment by shopgoodwill-auction-sniper** [comment]
Mr. Wick I have already tried to assist you to the best of our abilities but it seems you just keep on coming back and complaining so at this point we are no longer able to assist you. You are blocked from using our service now sorry!!!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mrwick16,

We apologize for that encounter you had with the previous customer service rep, we have relieved that customer service rep from their duties. I will be assisting you now, can you please try to installing Bid Sniper again from our Snipeable.com and if you have any further issues please let us know!

Thank you,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, 

We just released a new version tonight that solves the issue you are experiencing, please download and install it from our homepage at Snipeable.com 

Best Regards,
Technical Support

**Comment by mrwick16** [comment]
I just now noticed that I am no longer blocked after your rep told me to get lost. I am willing to try it again but I would like to get a license for three months for that extremely rude and uncalled for interaction. 
Not to mention the fact that I can see I wasn't the only one having the issues I referenced.
Please let me know.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Mr Wick,

You are welcome to use it, you can buy a 3 month license...

Best regards,
Customer Service

**Comment by mrwick16** [comment]
I am being reasonable here. I paid for the service that didn't work, asked for help and repeatedly tried to get your app that I paid money for to work and it only placed a bid one time. Then I was told to get lost after I required support. I have already paid for the service and have been denied support and blocked before. There is no way I would send you another dime without a legitimate show of good faith from you. 

See the screenshot of how your customer service rep handled it. To help I will write it out : "..so don't come complaining and demanding support, in fact, in order to assist you further you will need to pay for support now $249, and **no we don't offer refunds so either pay or get lost and stop wasting our time**'"
![Screenshot 2024-07-27 203302](https://github.com/user-attachments/assets/abb7e0b1-d001-4397-8f9f-c51d6bcd1478)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Mr. Wick,

I understand we let the customer service rep that assisted you go, but you don't understand we don't really have access to licenses 💯 all we can do here is fix issues.

**Comment by mrwick16** [comment]
Please go ahead & escalate the issue the person that can then. Again, it's a reasonable request for a show of good faith since the last license I paid for was invalidated and then I was refused support.

**Comment by shopgoodwill-auction-sniper** [comment]
Mr. Wick, we don't have access to licenses, all we can do is offer you a partial refund after you purchase.
