### ISSUE TITLE
Still not regersting bid.

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#23]
I downloaded the latest app as you suggested and still not working.

see pics below 

![IMG_3138](https://github.com/user-attachments/assets/8ab67c71-c2fb-4ef0-9b6e-f68396c19e55)
![IMG_3139 2](https://github.com/user-attachments/assets/32d2528d-bb05-40d2-8c5c-82c37fff9cff)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, 

We just released a new version tonight that solves the issue you are experiencing, please download and install it from our homepage at Snipeable.com 

Best Regards,
Technical Support
