### ISSUE TITLE
Updated, License didn't carry over.

### ISSUE THREAD

**Issue by Leovaliant** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#25]
Hello!

I bought a Lifetime License last year. Used it many times and worked great. I Just installed the latest version and the License didn't carry over, it's asking me to pay again.  Not sure how to locate or enter in my Lifetime License.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Leovaliant,

If you bought the license one year ago it has been outdated by the latest major release because we changed ownership and licenses! The new licensing system is installed onto to the computer that purchases it and it stays there so you will need to purchase again.

Best regards,
Customer Service

**Comment by Leovaliant** [comment]
When I purchased it on 8/28/2023 it didn't say anything about that, here's a screenshot of what it said.  I'm using the same PC and OS. You'd think you'd honor it. 

![Screenshot 2024-07-31 211843](https://github.com/user-attachments/assets/2b54b122-5dff-42b5-aca8-fec732b18ac5)

**Comment by shopgoodwill-auction-sniper** [comment]
We understand but the issue is the license itself is installed on the computer and we don't have no control over that!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Leovaliant,

One way you can re-activate your lifetime license is to purchase the life-time license again, and then we can refund your payment from here, keeping the license on your computer, while canceling your payment. That's the only option we have!

Best Regards,
Customer Service
