### ISSUE TITLE
LOST 4 Auctions

### ISSUE THREAD

**Issue by allieprop** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#29]
I downloaded the sniper, connected my goodwill account. bought 3 months unlimited snipes (to which never activated) then bought 5 more snipes, put in my auctions.   followed them. watched me snipe them. Then when looking at each auction I was not the winner of any. my bids never placed 
PLEASE ADVISE

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, did you hear the sniper sound play at all? Also what is your timezone?

**Comment by allieprop** [comment]
yes i heard sound, all 4 auctions say "SNIPED". last one that just ended showed NO BIds on GW site.

**Comment by allieprop** [comment]
I also paid for 3 months unlimited , missed the go back to merchant button, so I never got those credited, so I had 4 auctions happening tonight so I bought 5 more snipes. Dont know what has happend but I'm out $25 plus LOST ALL 4 AUCTIONS

**Comment by shopgoodwill-auction-sniper** [comment]
Did all 4 snipe sounds play exactly on time at the end of the auctions?

**Comment by allieprop** [comment]
i had a pop up window for the program that ran the sound and yes I do think at least 3 did pop up and make the sound

**Comment by shopgoodwill-auction-sniper** [comment]
But were they on time and are the auction end date times displayed correctly for the auctions?

**Comment by shopgoodwill-auction-sniper** [comment]
we have released a new update, please reinstall Bid Sniper by running the command on our homepage again at Snipeable.com and once it's reinstalled then purchase the 3 month unlimited again and once we receive your payment then we will refund it but it needs to go thru the software to give you the credits then try your bids again and let us know if it does or doesn't work this time... Please also try manually entering a bid into the shopgoodwill.com website to ensure there is no blockage going on with your account and bidding.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi allieprop,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
