### ISSUE TITLE
Wont bid

### ISSUE THREAD

**Issue by skratzer12** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#3]
I may be using the program wrong, I have the bid setup for 349.99. It shows loaded at the bottom of the screen for the item. 

The bid won with 341 and i was not the winning bid. 

Can you provide what went wrong or what i need to do differently? 

thanks! 

i have also paid and provided a month subscription.

**Comment by skratzer12** [comment]
I also got this error. 

Unhandled Promise Rejection
Error: Could not call remote method 'close'. Check that the method signature is correct. Underlying error: TypeError: Object has been destroyedUnderlying stack: TypeError: Object has been destroyed
    at C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:480:71
    at IpcMainImpl.<anonymous> (C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78929)
    at WebContents.emit (node:events:514:28)
    at C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:483:25
    at IpcMainImpl.<anonymous> (C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78929)
    at WebContents.emit (node:events:514:28)

**Comment by BuffySt** [comment]
yeah, we didn't get the product we paid for

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Buffy St,

We are currently working on this, we should have an update soon...

**Comment by skratzer12** [comment]
I paid for a month subscription, do I get a refund since what I bought
doesn't work?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi skratzer12,

Great news, we have released a new major version of Bid Sniper which fixes the issue you reported! You can download the latest version of the App Store here:

https://apps.microsoft.com/detail/9NLHNKNJM66J

**Comment by shopgoodwill-auction-sniper** [comment]
Hi skratzer12,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
