### ISSUE TITLE
need to purchase new license

### ISSUE THREAD

**Issue by skratzer12** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#32]
Hello, i could be missing it. 

I cannot locate where to purchase a new license after mine retires.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi skratzer12,

The software itself should prompt you to purchase a license, if it is not, then please update your sniper to the latest version by visiting our homepage at Snipeable.com and running the install/update command on our homepage again. Once you have updated to the latest version from our homepage then proceed to add a couple snipes and then it should ask you to buy a license.

Best regards,

Snipeable.com
Customer Service
