### ISSUE TITLE
can not download as an app with Mac

### ISSUE THREAD

**Issue by mmarici7** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#33]
Hello. When I try to download it, it just gives me a code. if I try to move it to my dashboard nothing changes. Please help!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

We have released the new version 24.08.30.1719 of the ShopGoodwill Sniper which resolves the issue you sent to us, you can download the new version by visiting our homepage at Snipeable.com and following the installation/update instructions on there.

Please let us know if we can be of further assistance.

Best regards,
Customer Service
Snipeable.com

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mmarici7,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
