### ISSUE TITLE
Not working on Win11 PC.

### ISSUE THREAD

**Issue by dlbjr** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#35]
Not working on Win11 PC.

![issue](https://github.com/user-attachments/assets/321baa7b-cd1d-4dbf-acfb-1821098470d3)

**Comment by shopgoodwill-auction-sniper** [comment]
Did you follow the installation instructions on our homepage?

**Comment by dlbjr** [comment]
Yes. Ran the power shell script. Ir completed and created the desktop icon.
I get the error when clicking the icon it worked before. I was installing
this because of the time zone issue update.
--from my personal mobile

David L. Bryant, Jr.

**Comment by shopgoodwill-auction-sniper** [comment]
Ok got it, we found the problem, we will have a fix up within the next few hours for you, we will notify you here when the new version is ready...

Thank you,
Technical Support
Snipeable.com

**Comment by dlbjr** [comment]
Ok. Thanks
--from my personal mobile

David L. Bryant, Jr.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

We have released the new version 24.08.30.1719 of the ShopGoodwill Sniper which resolves the issue you sent to us, you can download the new version by visiting our homepage at Snipeable.com and following the installation/update instructions on there.

Please let us know if we can be of further assistance.

Best regards,
Customer Service
Snipeable.com

**Comment by dlbjr** [comment]
Thanks


-My reply
*David L. Bryant, Jr.*

**Comment by shopgoodwill-auction-sniper** [comment]
Hi dlbjr,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
