### ISSUE TITLE
Says Node not found on Mac even though it's installed.

### ISSUE THREAD

**Issue by codingiswhyicry** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#37]
Hi, attempting to download on the Mac Terminal. I have Node installed for work and it shows up when I run `brew deps --tree --installed`. 

When running the script, it says it cannot complete the installation because Node can't be found. Output attached below. 

<img width="1399" alt="Screenshot 2024-09-02 at 8 25 03 PM" src="https://github.com/user-attachments/assets/9ebb9d66-9fc2-49e9-a1c9-695da9b2e89c">

<img width="197" alt="Screenshot 2024-09-02 at 8 24 45 PM" src="https://github.com/user-attachments/assets/09da693f-76cf-4d2e-94f7-c72e005ea2c0">

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Codingiswhyicry,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

You can update to the newest version by following the install/update instructions on our homepage at Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
