### ISSUE TITLE
Bought some snipes tried to use it but it did work at all. 

### ISSUE THREAD

**Issue by Advancedmart** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#38]
Says it worked but it did not bid at all. What gives?   I paid, but it did not bid at all.  says it did but it did not show any bids on the site. I lost the action bummer. 

![smiperScreenshot 2024-09-02 182131](https://github.com/user-attachments/assets/4339eb1d-a0d8-453c-95e4-8754458edafa)

![snipe2Screenshot 2024-09-02 182421](https://github.com/user-attachments/assets/f4414811-a7df-45fe-9436-1b5c0006605b)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Advancedmart,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

You can update to the newest version by following the install/update instructions on our homepage at Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
