### ISSUE TITLE
same as the others ... and paid the subscription fees

### ISSUE THREAD

**Issue by BuffySt** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#4]
Unhandled Promise Rejection
TypeError: Object has been destroyed
    at C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:503:56
    at IpcMainImpl.<anonymous> (C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.3.2622.0_x64__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78929)
    at WebContents.emit (node:events:514:28)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Buffy St,

We are currently working on this, we should have an update in about week or so...

**Comment by shopgoodwill-auction-sniper** [comment]
Hi BuffySt,

Great news, we have released a new major version of Bid Sniper which fixes the issue you reported! You can download the latest version of the App Store here:

https://apps.microsoft.com/detail/9NLHNKNJM66J

**Comment by shopgoodwill-auction-sniper** [comment]
Hi BuffySt,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
