### ISSUE TITLE
**URGENT** I already paid for Bid Sniper license but it keeps asking for new license

### ISSUE THREAD

**Issue by merchantmogul** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#5]
Hi, please see original issue I reported here: https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/issues/2

please scroll down to the very bottom.

When I try to use the new version it says I need to pay for license but i have alrady paid for a license.

Can you please fix this?

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/a410b1d7-b206-452c-aef6-708d49805bd1)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchant mogul,

We have re-activated your 6 month license on the new versions licensing system, so it shouldn't ask you anymore to pay again, please try it again now...


Best regards,
Customer Service

**Comment by merchantmogul** [comment]
But when I add a snipe I see this. what does "missed" mean??

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/a7b6d57b-4ac2-40de-8fe9-be0e8bd3e7b9)

**Comment by merchantmogul** [comment]
> But when I add a snipe I see this. what does "missed" mean??

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/5d3b3274-f4e7-4c43-a4ac-d0c92337c5fa)

**Comment by shopgoodwill-auction-sniper** [comment]
That means you missed the auction, it ended at 6:29pm it is 6:47pm now so you did not give it enough time, ensure you setup your snipes at least a few minutes before the auction ends...

**Comment by merchantmogul** [comment]
But does that for every single snipe I scheduled. all of the ones I schedule are in the future but it keeps saying "missed".

**Comment by merchantmogul** [comment]
I also have my snipes set to "never" expire. what does that mean? could that be the problem?

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/c7fcbdd7-3ad0-430b-bbe6-7d239273b927)

**Comment by merchantmogul** [comment]
Here's another example. I just scheduled this snipe. I am on EST time. on shopgoodwill all aucitons are on PST time. so 3 hours behind me. so 7pm PST is 10pm EST my time. but noticed eventhough this auciton is not over yet it still immediatly says "missed"

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/eb144cdf-097f-4045-9dff-0eb69414c054)

**Comment by merchantmogul** [comment]
![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/a5ab436d-2447-44c2-a1cf-542b1e233819)

**Comment by merchantmogul** [comment]
everytime I schedule a snipe it says "scheduled successfully". however, eveytime it says "missed" when I check it

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/a61a4e66-02cf-46d7-a544-7816d3980e06)

**Comment by merchantmogul** [comment]
there is something wrong with the software

**Comment by merchantmogul** [comment]
no matter how many I schedule and no matter what time in the future it keeps saying "missed"

![image](https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper/assets/160200040/3c61f607-dbcb-4b53-8133-c647a2bcde5c)

**Comment by merchantmogul** [comment]
those 2 acutions I just sent don't expire until about an hour from now. I'm on EST time zone

**Comment by shopgoodwill-auction-sniper** [comment]
does it say missed right away or does it say missed after the auctions ends?

**Comment by merchantmogul** [comment]
It says "missed" immediately. Every single time

**Comment by merchantmogul** [comment]
as soon as I click "scheduled" button it says "missed" instantly every time

**Comment by shopgoodwill-auction-sniper** [comment]
is the auction end datetime displayed correctly though in the my snipes section or does that date and/or time not match the shopgoodwill website?

**Comment by shopgoodwill-auction-sniper** [comment]
Never-mind my last question, I can see by your screenshots that the datetime is incorrect, so we have already found the issue and corrected and issued an update as well, it should be released and available for update in the App Store tomorrow!

**Comment by merchantmogul** [comment]
Ok. But if I install the new update will I lose my 6 month license like I have lost in the past? What do I do with that?

**Comment by shopgoodwill-auction-sniper** [comment]
The licensing has changed and now no longer is connected to the app but to the computer instead so it doesn't matter how many times you uninstall and reinstall it your license will still be there, however yesterday was a holiday and Microsoft still hasn't reviewed the new release so you will have to wait until they review and approve the release which could take a day or so, but once its released it will be available for update on the App Store...

**Comment by merchantmogul** [comment]
Ok. Can you let me know when the new update is available?

**Comment by shopgoodwill-auction-sniper** [comment]
> Ok. Can you let me know when the new update is available?

Yes, we are waiting for Microsoft to review and approve the update but they are closed weekends so it will most probably be on Monday or Tuesday...

**Comment by merchantmogul** [comment]
Hi, is the new update out now? is there a way to tell if the verison on the
store is the latest?

**Comment by shopgoodwill-auction-sniper** [comment]
No not yet, we are currently delayed about 1 week or 2...

**Comment by shopgoodwill-auction-sniper** [comment]
Hi merchantmogul,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
