### ISSUE TITLE
Still have not received a refund.

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#6]
I paid a total of $70.00,  I was told you would refund me so I could buy more snipes.  You never did.

**Comment by upnp-portmapper** [comment]
Hi, unfortunately we do not offer refunds, but I can assist you in activating your license if you like?

**Comment by shopgoodwill-auction-sniper** [comment]
Hi, unfortunately we do not offer refunds, but I can assist you in activating your license if you like?

**Comment by jake35th** [comment]
I paid a few months ago.  You said there was an issue with your app and would refund me so I could buy more snipes.  You never did.  How about giving me credit? Sent from my iPhoneOn Jul 6, 2024, at 7:12 PM, ShopGoodwill Auction Sniper ***@***.***> wrote:﻿
Hi, unfortunately we do not offer refunds, but I can assist you in activating your license if you like?

**Comment by shopgoodwill-auction-sniper** [comment]
Yes, absolutely, I can do that, which package did you buy?

**Comment by shopgoodwill-auction-sniper** [comment]
Please go ahead and download the new version from below and then copy and paste your machine id to me here so I can activate your new license: 

https://github.com/shopgoodwill-auction-sniper/shopgoodwill-bid-sniper

**Comment by jake35th** [comment]
I paid for a 6 months semi annual for 49.99 may 3rd.  The app was not
working so I deleted it and reinstalled it.  Not knowing the payment went
with it.

When It didn't work I then bought one month for 9.99 may 5th.  That did not
work as well, that's when I contacted you for a refund.

If you could credit me that would be great.  Let me know if you need
anything on my end.

Thanks

**Comment by shopgoodwill-auction-sniper** [comment]
yes, I can credit you but I need you to tell me your machine id so I can do that which is available the new version, you can download and upgrade here:

https://apps.microsoft.com/detail/9nlhnknjm66j

Once you installed the new version, please go ahead and add a couple items to your my snipes section and then it will automatically show you your machine id on the 2nd try, please copy and paste that machine id here so I can activate it.

**Comment by jake35th** [comment]
AFA5415035843E05Sent from my iPhoneOn Jul 6, 2024, at 9:03 PM, ShopGoodwill Auction Sniper ***@***.***> wrote:﻿
yes, I can credit you but I need you to tell me your machine id so I can do that which is available the new version, you can download and upgrade here:
https://apps.microsoft.com/detail/9nlhnknjm66j
Once you installed the new version, please go ahead and add a couple items to your my snipes section and then it will automatically show you your machine id on the 2nd try, please copy and paste that machine id here so I can activate it.

**Comment by shopgoodwill-auction-sniper** [comment]
Ok, I went ahead and gave you credits for 7 months from todays date!

**Comment by jake35th** [comment]
Thanks for your help. Sent from my iPhoneOn Jul 6, 2024, at 9:36 PM, ShopGoodwill Auction Sniper ***@***.***> wrote:﻿
Ok, I went ahead and gave you credits for 7 months from todays date!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi jake35th,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
