### ISSUE TITLE
Issue with Time Zones

### ISSUE THREAD

**Issue by dlbjr** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#7]
This does not work properly if your time zone is different than the time zone on the item for auction.
If an auction closes at 6 PM PDT and you are in Central Time. It should close at 8 PM. 
It will send a bid at 6 PM thanking it is closing.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi we are aware of the issue and have already created an updated fix for it however it has not been released yet, it should be released in a few days, I will notify you here when it's available...

**Comment by dlbjr** [comment]
Great!



--from my personal mobile

David L. Bryant, Jr.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi,

Thank you for your patience as we resolved the issue you reported and released an update for it, I am glad to report that the update is now released and you can download the latest version from our main page below, but first please uninstall the old version and then install the new version from here:

[http://Snipeable.com](http://Snipeable.com)

**Comment by shopgoodwill-auction-sniper** [comment]
Hi dlbjr,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
