### ISSUE TITLE
Login disappeared

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#8]
The login info on the upper right has disappeared. 

I also have "The service is unavailable." under the search bar.

**Comment by jake35th** [comment]
I opened and closed the program a few times, nothing.  Restarted the computer and it back.

**Comment by shopgoodwill-auction-sniper** [comment]
try right clicking in the center of the browser where it says this service is unavailable and click refresh, that will refresh the page if not just type in the homepage url in the address bar above and hit enter on your keyboard... the shopgoodwill website goes down sometimes...
