### ISSUE TITLE
Paid for license but still saying not activated

### ISSUE THREAD

**Issue by alexr544** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#9]
![image](https://github.com/user-attachments/assets/1d62f8f3-b3e6-4244-9580-dd0c2369b068)

Can you help activate it please?

**Comment by shopgoodwill-auction-sniper** [comment]
Hello alexr544,

We have activated your 1 month unlimited license, please let us know if we can be of further assistance!

Best regards,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi alexr544,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
